rbac:
  create: true

controller:
  config:
    ssl-protocols: TLSv1.3 TLSv1.2
    ssl_ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
    ssl_ecdh_curve: secp384r1
    hsts: "true"
    hsts-include-subdomains: "true"
    hsts-max-age: "31536000"
    hsts-preload: "true"
    log_format: json

  publishService:
    enabled: true

  minReadySeconds: 5

  readinessProbe:
    failureThreshold: 1

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 64Mi

defaultBackend:
  minAvailable: 0
  service:
    type: ClusterIP
    clusterIP: None
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi
