{{- range .Values.certificates }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "tls.fullname" $ }}-{{ .nameSuffix }}
  labels:
    {{- include "tls.labels" $ | nindent 4 }}
spec:
  secretName: {{ include "tls.fullname" $ }}-{{ .nameSuffix }}
  issuerRef:
    name: {{ include "tls.fullname" $ }}-{{ .issuerNameSuffix }}
    kind: {{ .issuerKind }}
  commonName: {{ tpl .commonName $ }}
{{- end }}
