{{- range .Values.issuers }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: {{ .kind }}
metadata:
  name: {{ include "tls.fullname" $ }}-{{ .nameSuffix }}
  labels:
    {{- include "tls.labels" $ | nindent 4 }}
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ include "tls.fullname" $ }}-{{ .nameSuffix }}
    solvers:
      {{- tpl .solvers $ | nindent 6 }}
{{- end }}
