jenkins:
  securityRealm:
    local:
      users:
        - id: "${ADMIN_USER}"
          password: "${ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  numExecutors: 0
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  clouds:
    - kubernetes:
        name: kubernetes
        serverUrl: https://kubernetes.default
        namespace: {{ .Release.Namespace }}
        jenkinsUrl: http://{{ include "jenkins.fullname" . }}-master:{{ .Values.service.master.port }}
        jenkinsTunnel: {{ include "jenkins.fullname" . }}-agent:{{ .Values.service.agent.port }}
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  shell:
    shell: /bin/bash
  location:
    url: https://{{ .Values.jenkinsDomain }}
  timestamperConfig:
    systemTimeFormat: "'<b>'yyyy-MM-dd HH:mm:ss.SSS'</b> '"
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    allPipelines: true
jobs:
  - file: /var/jenkins_home/jobdsl/job.groovy
